title:  <p align="center"> Akshay Kachroo </p>
logo: /assets/img/akshay.png
description:
  <p align="center">
  <a href="/assets/CV - Akshay Kachroo_june23.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/akshay-kachroo/">LinkedIn</a> |
  <a href="https://github.com/kachrooakshay95">GitHub</a>
<br>   
  I'm a hardcore Data Scientist, having 6+ years of relevant experience .
  I have worked on end-to-end ML pipeline for various domains.
  Worked in client facing roles of top consulting firms.
  Working in Healthcare domain for 3 years.
  <br>
  </p>

theme: jekyll-theme-minimal
