title: <p align="center"> Akshay Kachroo </p>
logo: /assets/img/akshay.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/akshay-kachroo/">LinkedIn</a> |
  <a href="https://github.com/kachrooakshay95">GitHub</a>
  
  <br>   
  I am a hardcore data scientist having 6+ years of overall experience.
  I have worked on end to end ML pipeline.
  I have 3+ years of working in healthcare domain.
  <br>
  </p>



theme: jekyll-theme-minimal
